variable "priv_sn1" {}
variable "jenkins_sg" {}
variable "docker_tg_name" {}
variable "jenkins_server" {}
variable "jenkins-lb-name" {}
variable "docker_sg" {}
variable "docker-lb-name" {}
variable "vpc_id" {}
variable "priv_sn2" {}